Feat/77555 77680 change ogp image
weseek/growi-unique-ogp pull request #1
Opened 2021-12-08 10:11 UTC by yuto-oweseek

2021-12-08 10:15 UTC, yuto-oweseek commented on src/index.js
> +    // TODO: refactor and adjust design after ogp design is created
仮表示なので、ここらへんのコードと不要なコードは、OGP の画像をデザイナーさんからもらい次第、調整します。

2021-12-09 10:22 UTC, yuki-takei requested changes

2021-12-09 10:22 UTC, yuki-takei commented on src/index.js
> +        })
この辺のは createServer の callback に直に書かずにメソッドとして分割させてほしいな。

2021-12-13 07:18 UTC, yuto-oweseek commented on src/index.js
> +        })
- controller を用意し、 async 方式にしました
- 不要なメソッドや、マジックナンバー的な数値宣言などは canvas で画像を生成するタスクで調整します

2021-12-13 07:20 UTC, merged