feat: add eslint
weseek/growi-unique-ogp pull request #11
Opened 2022-01-19 09:17 UTC by yuto-oweseek

## タスク

https://redmine.weseek.co.jp/issues/85865

## 行ったこと

- devcontainer 環境で eslint を導入しました

2022-01-19 09:26 UTC, yuto-oweseek commented on .devcontainer/devcontainer.json
> +  "name": "GROWI-OGP-Dev",
このファイルは、`.editorconfig` によってスペースが変更されたのと、↓の settings に eslint を導入しました。

```
  "settings": {
    "[javascript]": {
      "editor.formatOnSave": false
		},
    "editor.codeActionsOnSave": {
      "source.fixAll.eslint": true,
    }
  },
```

2022-01-19 09:26 UTC, yuto-oweseek commented on src/.eslintrc.js
> +    'weseek/typescript',
typescript は使ってないですが、commonJS の `const a = require('module')` の箇所で eslint からエラーが出てしまうので追加しました。

2022-01-19 09:26 UTC, yuto-oweseek commented on src/index.js
>  const http = require('http');
このファイルは eslint のコーディング規約による変更です。

2022-01-19 09:26 UTC, yuto-oweseek commented on src/growi-ogp-drawer.js
> -const Canvas = require('canvas');
このファイルは eslint のコーディング規約による変更です。

2022-01-19 10:04 UTC, yuto-oweseek commented on src/.eslintignore
> +node_modules/**
docker の named volume してる場所がミスってることに気づいたので、後続タスクで修正します。

2022-01-19 11:06 UTC, yuki-takei requested changes

2022-01-19 11:06 UTC, yuki-takei commented on src/.eslintrc.js
> +    'weseek/typescript',
どういうエラー？

2022-01-20 06:12 UTC, yuto-oweseek commented on src/.eslintrc.js
> +  parser: '@babel/eslint-parser',
`require` を Eslint が禁止していたのは、eslint-config-weseek 側で ` parser: 'babel-eslint'` を使っているのが原因と分かりました。

そのため、このファイルで parser を上書きすることにしました。
parser 以外は eslint-config-weseek から設定が引き継がれています。

2022-01-20 09:02 UTC, yuki-takei approved these changes

2022-01-20 09:02 UTC, yuki-takei commented on src/.eslintrc.js
> +  parser: '@babel/eslint-parser',
- 具体的にどういうエラーかここにも書いて欲しかった。(テキストで)
- 参考サイトがあるならここに貼って欲しかった
    - 例えば https://stackoverflow.com/a/69557309 とか
- 後続ストーリーで、eslint-config-weseek 側を進化させてほしい
    - 新バージョンリリース
    - 新バージョンの eslint-config-weseek を適用して、不要になった記述を消す

2022-01-20 09:02 UTC, merged