feat: prepare ci cd but this will be improved
weseek/growi-unique-ogp pull request #3
Opened 2021-12-15 09:33 UTC by yuto-oweseek

## タスク

https://redmine.weseek.co.jp/issues/83248

## 行ったこと

## 後続

- canvas でデザインを整えて出力&不要なコードの削除
- CI/CD のブラッシュアップ(Lintを入れる、サーバーに対してのテストを入れるなど)

2021-12-15 09:45 UTC, yuto-oweseek commented on .github/workflows/ci.yml
> +      # TODO: check if server runs properly
- lint チェック(lint を devcontainer に入れないと必要な行などが分からず手間のため)
- サーバーが立ち上がっているのかテスト

上記2つを後続タスクで行いたいです。

2021-12-15 10:16 UTC, yuto-oweseek commented on .github/workflows/release.yml
> +      # TODO: push to dockerhub
この PR 内で dockerhub への push は行う

2021-12-15 10:16 UTC, yuki-takei requested changes

2021-12-15 10:16 UTC, yuki-takei commented on .github/workflows/ci.yml
> +        uses: actions/checkout@v2
キャッシュ効かせてください

2021-12-15 10:16 UTC, yuki-takei commented on .github/workflows/ci.yml
> +        node-version: [12.x]
古いので後続タスクでアップグレードして。

2021-12-16 11:07 UTC, yuto-oweseek commented on .github/workflows/ci.yml
> +        node-version: [12.x]
i add todo comment and create task in redmine

2021-12-20 06:34 UTC, yuto-oweseek commented on .github/workflows/ci.yml
> +        uses: actions/checkout@v2
```
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
```
↑を追加しました。

2021-12-20 06:53 UTC, yuto-oweseek commented on .github/workflows/release.yml
> +      - name: Build and push
release** の branch にマージされた時のみ build and push を行う設定なんですが、こういう場合も、キャッシュは効かせたほうがいいですか？(必要なかったら無視してください)

必要であれば、後続の ci に lint や server が起動しているかのテストを追加するタスクで行いたいと思います。

2021-12-20 08:45 UTC, merged