wip: add eslint and prettierrc and this works
weseek/growi-unique-ogp pull request #6
Opened 2022-01-05 11:55 UTC by yuto-oweseek

wip 😭

2022-01-06 09:10 UTC, yuto-oweseek commented on src/package.json
> +    "test": "echo \"Error: no test specified\" && exit 1",
jest を後続で追加予定です。

2022-01-06 09:10 UTC, yuto-oweseek commented on src/index.js
> +import http from 'http';
このファイルの差分は babel を使って ES を使うようにしたのと、 Eslint & prettier で若干コードの細かい箇所が修正されたものです。

2022-01-06 09:10 UTC, yuto-oweseek commented on .devcontainer/devcontainer.json
> +{
Eslint のルールと prettier のコード自動修正の共存には eslint-config-prettier を使いました。

2022-01-06 10:04 UTC, yuto-oweseek commented on .github/workflows/ci.yml
> +      - name: npm install for app source directory
babel-cli と babel-preset-env が src 側にあるので、./src も npm install してます

2022-01-06 12:48 UTC, yuki-takei requested changes

2022-01-06 12:48 UTC, yuki-takei commented on .devcontainer/devcontainer.json
> +{
GROWI 本体踏襲してください。prettier は scss にしか使わない。

2022-01-06 12:48 UTC, yuki-takei commented on package.json
> +    "babel-eslint": "^10.1.0",
babel 不要なんじゃないかな

2022-01-06 12:48 UTC, yuki-takei commented on src/package.json
> +    "babel-preset-env": "^1.7.0",
こっちもなぜ babel がいるのか？

2022-01-06 12:52 UTC, yuki-takei requested changes

2022-01-06 12:52 UTC, yuki-takei commented on .devcontainer/Dockerfile
> +    && apt-get install -y git python3 build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev fonts-noto-cjk
GROWI 踏襲してください。

`FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:...` を使えば git, python, build-essential やらはいらないはず。

2022-01-06 12:52 UTC, yuki-takei commented on Dockerfile
> +ENTRYPOINT ["npm", "start"]
後続ストーリーでマルチステージビルド化したい。

2022-01-14 07:08 UTC, yuto-oweseek commented on .devcontainer/devcontainer.json
> +{
scss は OGP サーバーで使わないので、 prettier は入れずに eslint のみ使う方針にしました。

2022-01-14 07:08 UTC, yuto-oweseek commented on Dockerfile
> +ENTRYPOINT ["npm", "start"]
承知です。

ストーリー化しました。

2022-01-14 07:08 UTC, yuto-oweseek commented on package.json
> +    "babel-eslint": "^10.1.0",
https://github.com/weseek/eslint-config-weseek

ここ見ると、↓のように書いてあるんですけど、growi 本体側の package.json に `babel-eslint` がおらず、うまく真似できず、「動く目的」にして babel を使うところに至りました。

```
Entry Points
weseek - Our default ESLint rules based on airbnb-base.
Requirements
babel-eslint
eslint-plugin-import
```

babel なしだとちょっと時間かかってしまいそうなので、babel なしにすることが必要の場合は後続ストーリーにしたいです。

2022-01-14 07:08 UTC, yuto-oweseek commented on src/package.json
> +    "babel-preset-env": "^1.7.0",
- アプリのルートディレクトリ側: eslint の parser として dev 環境で使う babel
- こっち側の babel は実行？ES にトランスパイル？するための babel

という感じです。

2022-01-14 07:12 UTC, yuto-oweseek commented on .devcontainer/Dockerfile
> +    && apt-get install -y git python3 build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev fonts-noto-cjk
`FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:...`に変更しました。
神でした。

2022-01-14 07:31 UTC, yuki-takei requested changes

2022-01-14 07:31 UTC, yuki-takei commented on .devcontainer/docker-compose.yml
> +      - ..:/workspace/growi-ogp:delegated
node_modules を named volume にして

2022-01-14 07:31 UTC, yuki-takei commented on src/package.json
> +    "babel-preset-env": "^1.7.0",
babel が eslint で必要なのであれば、devDependencies に入れる。
かつ、packages.json を分ける必要は無い。

2022-01-14 07:31 UTC, yuki-takei commented on Dockerfile
> +ENTRYPOINT ["npm", "start"]
本番環境での npm の起動は bad practice

2022-01-14 07:31 UTC, yuki-takei commented on src/package.json
> +    "start": "babel-node ./index.js"
babel-node での起動は bad practice

2022-01-14 12:22 UTC, yuto-oweseek commented on .devcontainer/docker-compose.yml
> +      - ..:/workspace/growi-ogp:delegated
こっちの pr で　行いました

https://github.com/weseek/growi-unique-ogp/pull/9

2022-01-27 08:55 UTC, closed without merging